### ISSUE TITLE
Connection not working with Tableau Server V. 2021.3.0

### ISSUE THREAD

**Issue by piatto-evision** [analytikaplus/clickhouse-tableau-connector-jdbc#15]
Hi, nice connector!

I tried to install version v0.1.2. on Tableau Server version: 2021.3.0 (20213.21.0902.2150) 64-bit Linux

When I run the connection test, published by Tableau Desktop, it tells me that it is "unable to connect to the Server".
I also confirm that the connector is not present among those selectable when creating a workbook.

With Tableau Server Version: 2020.3.1 (20203.20.0918.1727) 64-bit Linux on the other hand works perfectly, connects and allows the construction of dashboards without problems

Does this only work with the 2020 releases of Tableau Server?

Are you planning to develop it also for the 2021 version?

Thanks

**Comment by yurifal** [comment]
Could you please try the latest version 0.1.3 ?

**Comment by artshevchenko** [comment]
Hi! Thank you!

I checked the connector v0.1.2 with Tableau Server version 2021.3.3 (Linux, CentOS) and it works fine. Most likely you forgot to do some steps from the instructions, I recommend re-installing the connector.

<img width="1440" alt="Screenshot 2021-11-12 at 15 34 12" src="https://user-images.githubusercontent.com/9002056/141468789-a1b8b430-710b-4ccd-8ee5-b46e3e7d1fd3.png">

**Comment by piatto-evision** [comment]
Hi artshevchenko and thanks for the reply.

I followed the instructions from https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc#how-to-install-tableau-server

I installed clickhouse-jdbc-0.3.1-patch-shaded.jar and clickhouse_jdbc.taco version v0.1.2 on Tableau Server version: 2021.3.0 but on Linux Debian v.9.13, could it be a problem related to the operating system?
Are there any other precautions to consider when installing on Debian v.9.13 ??

Thank you for your reply and support.

**Comment by piatto-evision** [comment]
Could it be a problem related to the connections allowed by the license installed on the Tableau Server? ... Should it be classified as a "GJDBC" connection?

Thanks for the attention

**Comment by artshevchenko** [comment]
These may be problems related to the restriction on 5 types of Tableau Server connections in the Embedded Analytics use case, since our connector is not Generic JDBC. However, colleagues from Tableau removed this restriction on November 2, 2021, and if you have an Embedded Analytics installation, you should update your keys: https://help .tableau.com/current/server/en-us/license_refresh.htm

You can get detailed information about this from your Tableau partner.

**Comment by piatto-evision** [comment]
Hi artshevchenko,
I confirm that the problem is related to the restriction on 5 types of Tableau Server connections in the Embedded Analytics use case.

After updating the licenses everything works perfectly.

Thank you for your help and for the great job you are doing with this connector.
