### ISSUE TITLE
Named session error

### ISSUE THREAD

**Issue by skaradub** [analytikaplus/clickhouse-tableau-connector-jdbc#16]
Hello there!

connector is nice, but some instances got error with such text:
![image](https://user-images.githubusercontent.com/57046561/141461521-f0e1da31-bcef-4507-a816-b5619fb53650.png)

ClickHouse exception, code: 48, host: mstat-ch-cache.vs.market.yandex.net, port: 443; Code: 48, e.displayText() = DB::Exception: Support for named sessions is not enabled (version 21.6.1.1-arcadia)

I understand that the cause is our settings on cluster, but could it be possible to have checbox not to send session_id  while connecting to srver?

regards,
Yury

**Comment by artshevchenko** [comment]
Hi! This will be fixed soon in v0.1.3. We will add a custom parameter to disable session_id. Stay tuned!

**Comment by artshevchenko** [comment]
Hi! The release is already available [here](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/releases/tag/v0.1.3)
