### ISSUE TITLE
Package signature verification failed

### ISSUE THREAD

**Issue by dubiousdavid** [analytikaplus/clickhouse-tableau-connector-jdbc#19]
```
Package signature verification failed during connection creation.
Connector Class: clickhouse_jdbc, Version: 0.1.3
For support, contact ANALYTIKA PLUS.
```

**Comment by yurifal** [comment]
Desktop or Server? 
What's the Version? 
What's the OS it's on?

**Comment by dubiousdavid** [comment]
Tableau Desktop
Clickhouse JDBC Driver: v0.3.1-patch
clickhouse-tableau-connector-jdbc: 0.1.3
OS: MacOS 12.0.1 (M1)

**Comment by dubiousdavid** [comment]
BTW,  I tried all versions of `clickhouse-tableau-connector-jdbc` starting with 0.1.0.

**Comment by artshevchenko** [comment]
Hi! Looks like Comodo (Sectigo) root certificate is not installed on your Mac

**Comment by dubiousdavid** [comment]
Is there an article or documentation that you can point me to in order to install the needed root certificate?

**Comment by dubiousdavid** [comment]
I have these three installed. Which one am I missing?

<img width="833" alt="2021-12-01_11-17-34" src="https://user-images.githubusercontent.com/1327969/144271521-12a3371d-4eac-44d1-a29b-067bf1b87e5f.png">

**Comment by dubiousdavid** [comment]
https://sectigo.com/resource-library/sectigo-root-intermediate-certificate-files

**Comment by artshevchenko** [comment]
Ok. You can try to install these certificates:
![A2919B0D-7EAA-496F-920E-A260D2B69DCF](https://user-images.githubusercontent.com/9002056/144277691-534732fe-017b-4146-922c-96213fc26984.jpeg)

- [Sectigo (AAA)](http://www.tbs-x509.com/Comodo_AAA_Certificate_Services.crt)
- [Sectigo Public Code Signing Root R46](https://sectigo.tbs-certificats.com/SectigoPublicCodeSigningRootR46.crt)
- [Sectigo Public Code Signing CA R36](https://sectigo.tbs-certificats.com/SectigoPublicCodeSigningCAR36.crt)

**Comment by dubiousdavid** [comment]
That didn't work for me.

**Comment by artshevchenko** [comment]
Hi! It looks like you are using Tableau Desktop 2021.3.4, a problem caused by a bug in this version of Tableau Desktop. Please try Desktop 2021.3.4 instead.

**Comment by yurifal** [comment]
The problem may exist in every minor patch update as of 30-Nov-2021.
The (Tableau Support) Case has been opened today.
