### ISSUE TITLE
Подключение через коннектор СH JDBC

### ISSUE THREAD

**Issue by NickVizuators** [analytikaplus/clickhouse-tableau-connector-jdbc#20]
Добрый день, пытаемся подключится с помощью вашего коннектора и наталкиваемся на такую ошибку. Подскажите, пожалуйста, как можно подключиться?
![234](https://user-images.githubusercontent.com/96234103/146347071-54b1081b-e706-4c0b-a524-1ccdfb5fee33.png)

**Comment by yurifal** [comment]
По какому протоколу и порту подключаетесь?

**Comment by NickVizuators** [comment]
General и 443

**Comment by yurifal** [comment]
у КХ по умолчанию http  через 8123, а https (флаг SSL  в коннекторе) 8443

**Comment by NickVizuators** [comment]
Коллега подключился по этим же параметрам, все подключилось

**Comment by yurifal** [comment]
тогда попробуйте сравнить, чем отличается подключение у Вас и у Вашего коллеги.
в том числе версия Табло, версия JDBC драйвера, имя пользователя, ну и все остальное.
если имя хоста (сервера КХ) одно и то же, то можете его замазать, и показать картинкой 
диалог подключения (свой и коллеги)?

**Comment by artshevchenko** [comment]
@NickVizuators, привет! Получилось разобраться?
