### ISSUE TITLE
Не удается подключиться из-за проблем с SSL

### ISSUE THREAD

**Issue by KostasSpirliev** [analytikaplus/clickhouse-tableau-connector-jdbc#22]
Привет!
Можете подсказать, пожалуйста, пытаюсь подключиться, но мне выдает такую ошибку:

An error occurred while communicating with ClickHouse JDBC by ANALYTIKA PLUS
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5
ClickHouse exception, code: 1002, host: sas-zy002mb3vw503gg2.db.yandex.net, port: 8443; PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Unable to connect to the ClickHouse JDBC by ANALYTIKA PLUS server "sas-zy002mb3vw503gg2.db.yandex.net". Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.1.4

При условии, что я могу подключиться через SSL по ODBC через Tableau, и по JDBC через datagrip (с и без указания пути к сертификату; нужные сертификаты уже установлены).

Версия драйвера: пробовал через 0.3.2-patch-1, 0.3.1
Версия коннектера: 0.1.4
MacOS: 11.6.1
Tableau: пробовал через 2021.2 и через 2021.4

**Comment by yurifal** [comment]
Для macOS и Yandex.cloud придется пропатчить сам Tableau Desktop. Вот так: 

`sudo /Applications/Tableau\ Desktop\ 2021.4.app/Contents/Plugins/jre/bin/keytool -import -alias yandex -keystore /Applications/Tableau\ Desktop\ 2021.4.app/Contents/Plugins/jre/lib/security/cacerts -file /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt`

будет запрошен пароль для **Java keystore**, обычно это `changeit`

**Comment by KostasSpirliev** [comment]
спасибо, получилось!
