### ISSUE TITLE
Не удается подключиться из-за проблем с SSL на Windows

### ISSUE THREAD

**Issue by MaximEvdokimov** [analytikaplus/clickhouse-tableau-connector-jdbc#23]
Добрый день! Пытаюсь подключиться через новый драйвер, вижу такую ошибку

An error occurred while communicating with ClickHouse JDBC by ANALYTIKA PLUS
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5

ClickHouse exception, code: 1002, host: sas5-2953-proxy-hahn.sas.yp-c.yandex.net, port: 80; Unsupported or unrecognized SSL message
Unable to connect to the ClickHouse (JDBC) by ANALYTIKA PLUS server "sas5-2953-proxy-hahn.sas.yp-c.yandex.net". Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.1.1
For support, contact ANALYTIKA PLUS.

Через обычный драйвер ODBC подключаюсь без проблем

Версия коннектера: 0.1.1
OC: Windows 10
Tableau: пробовал через 2020.4.9

**Comment by yurifal** [comment]
Попробуйте использовать версию 0.1.4 коннектора.
И встречный вопрос -- какой протокол используете? http или https?

**Comment by MaximEvdokimov** [comment]
Попробовал 0.1.4, текст ошибки немного поменялся

No enum constant com.clickhouse.client.config.ClickHouseSslMode.strict
Unable to connect to the ClickHouse JDBC by ANALYTIKA PLUS server "sas5-2953-proxy-hahn.sas.yp-c.yandex.net". Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.1.4
For support, contact ANALYTIKA PLUS.

**Comment by MaximEvdokimov** [comment]
Используем https, да

**Comment by yurifal** [comment]
еще два вопроса тогда: 
1) по какому порту подключаетесь (8123 или 8443)?
2) в коннекте через ODBC ставите флаг SSL?

**Comment by MaximEvdokimov** [comment]
Тут наверно нужно уточнение - подключаюсь не к чистому Clickhouse, а к Clickhouse over Yandex Tables
но меня уверяют, что с точки зрения внешнего инструмента это должно быть аналогично Clickhouse

Поэтому параметры такие:

1. Если подключаться через ODBC, то коннект идет через порт 80.   Попробовал сейчас остальные 2 порта, ошибка такая же

**Comment by yurifal** [comment]
пожалуйста, попробуйте комбинацию 
коннектор 0.1.4 (релиз)
JDBC драйвер 0.3.1-patch

fyi с драйвером 0.3.2-patch1 
нужно будет использовать 
коннектор версии 0.2.0 
(который еще не выложен в релиз)

**Comment by yurifal** [comment]
вот кстати и релиз 0.2.0 подоспел. 
тестируйте пожалуйста.

**Comment by MaximEvdokimov** [comment]
Юрий, добрый день!

переехал на указанные вами версии
драйвер 0.3.2-patch1
коннектор версии 0.2.0

**Comment by MaximEvdokimov** [comment]
Юрий, добрый день!

переехал на указанные вами версии
драйвер 0.3.2-patch1
коннектор версии 0.2.0

Unsupported or unrecognized SSL message, server ClickHouseNode(addr=http:sas1-2859-proxy-hahn.sas.yp-c.yandex.net:80, db=default)@1761184179
Unable to connect to the ClickHouse JDBC by ANALYTIKA PLUS server "sas1-2859-proxy-hahn.sas.yp-c.yandex.net". Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.2.0

Ошибка в целом остается примерно такая же.
Попробовал также явно прописать путь драйвера на вкладке Advanced, ничего не меняется
если вбить путь неправильно, то  ошибка меняется на  javax.net.ssl.SSLException: Failed to get SSL context

Еще есть вопрос к строке db=default в описании ошибки, по идее нужно уметь выбирать также базу на сервере, но такой опции не вижу
попробовал на вкладке Advanced также добавить что - то в стиле db=my_db_name во все параметры, но тоже ничего не происходит. 
Есть способ указать правильную базу?

**Comment by artshevchenko** [comment]
Добрый день! database=my_db_name

**Comment by yurifal** [comment]
покажите, куда и какой строкой прописан путь к корневому сертификату Яндекса.
у меня на экране с примером это:  

куда прописано: JDBC Driver URL Parameters
что прописано:   sslrootcert=/etc/ssl/certs/YandexInternalRootCA.crt

у Вас windows, поэтому сам сертификат можно положить на C: в корень, 
и тогда строка будет вот такая:  sslrootcert=/YandexInternalRootCA.crt

у меня при такой настройке Tableau Desktop коннектится по https (8443) 
к экземпляру КХ, который развернут как Managed Database Instance в Я.Облаке.

У Вас перед ним стоит прокси, так что вполне возможно, что моя настройка не сработает.

**Comment by MaximEvdokimov** [comment]
сертификат лежит чуть глубже, чем в корне, путь указываю вот такой:

![image](https://user-images.githubusercontent.com/97674421/149741025-d6dcbfe1-eea2-4c51-9a06-6707c8bb160d.png)

**Comment by yurifal** [comment]
лучше именно в корень положить -- тогда при публикации 
на Tableau Server можно абстрагироваться от ОС (windows или linux).

database=*ch_public  положите (пока что) тоже в URL Parameters -- 
потом можно будет их переместить выше, если коннект заработает.

и добавьте в URL Parameters еще вот такие (через запятую есно):

path=/query,check_for_redirects=1,use_path_as_db=1

**Comment by MaximEvdokimov** [comment]
Переложил сертификат в корень, перенес database=*ch_public  в URL parameters, добавил path=/query,check_for_redirects=1,use_path_as_db=1
Ошибка пока такая же
Попробую еще кого-то попросить подключиться для сбора статистики


Unsupported or unrecognized SSL message, server ClickHouseNode(addr=http:sas1-2859-proxy-hahn.sas.yp-c.yandex.net:80, db=*ch_public)@642150491
Unable to connect to the ClickHouse JDBC by ANALYTIKA PLUS server "sas1-2859-proxy-hahn.sas.yp-c.yandex.net". Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.2.0

![image](https://user-images.githubusercontent.com/97674421/149760734-17b916a9-56be-4592-aed4-9bfaedf998f1.png)

**Comment by yurifal** [comment]
у меня стойкое ощущение, что прокси с клиентом хочет общаться по **http** (без SSL)

**Comment by artshevchenko** [comment]
Так и не получилось подключиться?
