### ISSUE TITLE
Package signature verification failed. Tableau Server

### ISSUE THREAD

**Issue by max-zorn** [analytikaplus/clickhouse-tableau-connector-jdbc#25]
Hello. I did everything according to the instructions, installing the latest versions of the driver and connector, but get the following error:

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/40857648/150849101-fe713778-393e-47ce-a750-f02498d87592.png">

Linux 4.15.0-55-generic x86_64
clickhouse-jdbc-0.3.2-patch2-shaded.jar
clickhouse_jdbc_0.2.1.taco

<img width="469" alt="image" src="https://user-images.githubusercontent.com/40857648/150848460-9c528077-29a9-48ec-9890-871e0c795874.png">

How can it be fixed?

**Comment by yurifal** [comment]
The screenshot you've provided looks like the one of the **previous** version of the Connector 
(something like 0.1.1 or less). The error is about the Connector (*.taco) file not to be signed properly.

Please make sure you've installed and activated the newest release (version 0.2.1 as of now).

**Comment by artshevchenko** [comment]
Hi! Which version of Tableau Server are you using?

**Comment by max-zorn** [comment]
@yurifal thank you, re-starting tsm helped to fix this issue. But I received another error:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/40857648/150859563-33a4eb6c-a284-478f-9095-28e97deb8128.png">

I use the same credits on the server as for the Tableau desktop where the connection works. Should I open a new ticket for this error?

@artshevchenko Tableau Server Version: 2021.4.1 (20214.21.1214.2057) 64-bit Linux

**Comment by yurifal** [comment]
As far as I know, the connections on the http protocol (port 8123) 
to the CH managed instances hosted in the Yandex Cloud network 
are allowed from the hosts belonging to the same net (Y.Cloud only).
The 'external' connections have to be using https (port 8443) and SSL.
Please check the subnet of the host running your Tableau Server 
(as compared to the computer with the Tableau Desktop).

**Comment by artshevchenko** [comment]
@max-zorn Hi!
Did Yuri's comment help? I found [the proof in the documentation.](https://cloud.yandex.com/en/docs/managed-clickhouse/operations/connect)

**Comment by yurifal** [comment]
Please refer to this my comment (and the picture of the Advanced tab):
https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/issues/23#issuecomment-1013135359
