### ISSUE TITLE
Wrong installation instructions for Windows 10

### ISSUE THREAD

**Issue by shhhidan** [analytikaplus/clickhouse-tableau-connector-jdbc#27]
In README in section **How to install (Tableau Desktop)** you offer to install file `clickhouse-jdbc.taco` at directory:

- Windows: `C:\Users\[Windows User]\Documents\My Tableau Repository\Connectors`

That doesn't work on my Windows 10 Home Edition (21H2): Tableau Desktop doesn't see the connector.
The correct folder to place this file is 
`C:\Users\[Windows User]\OneDrive\Документы\My Tableau Repository\Connectors`
If you place the file here everything starts to work well. 

PS: I don't know how but Altinity has managed to place their ODBC connector here without any issues. Maybe you should consider to write your own MSI-installer which will do that dirty job for you under the hood.

**Comment by yurifal** [comment]
Yep, you're right, the absolute path would be different for Win users syncing Documents to OneDrive.
We will make changes to the README. 
Closing the issue for now.
