### ISSUE TITLE
Can not connect clickhouse after publishing the prep flow to Tableau Server

### ISSUE THREAD

**Issue by kaihg** [analytikaplus/clickhouse-tableau-connector-jdbc#29]
Dear Analytika:
I'm very like your JDBC driver of tableau, it helps me a lot. It work perfectly on client, but there is a issues on server.

I would like to create a flow with a Clickhouse data source in Prep. The data source connector is work so I can see my data on Prep. But when I publish my flow to tableau server and run the flow, the error occurs.
The error message is nothing but only say "connect error". I tried publishing my desktop sheet to server, and it can work. Only the data source in flow is not worked.

**Environment:**
Tableau Server: Linux 2021.4.4
Prep: 2021.4.4 (on Windows)
JDBC driver: [Release v0.3.2-patch6](https://github.com/ClickHouse/clickhouse-jdbc/releases/tag/v0.3.2-patch6)

**Comment by yurifal** [comment]
Hi @kaihg 

I was able to reproduce your case. 

Additional tests would be required 
(CH ODBC Connector by Altinity, 
other connectors from the Gallery).

You could do test the ODBC, too.

**Comment by kaihg** [comment]
Hi @yurifal 

I tried the ODBC connector by Altinity, but there was the same issue. I also tried the default ODBC, JDBC connctor by Tableau, still error like the image.
![image](https://user-images.githubusercontent.com/5411167/159213539-3132d1eb-1617-4ec0-9ed6-190bcdd2863e.png)
![image](https://user-images.githubusercontent.com/5411167/159213590-700cd37f-2cfc-417c-888b-e9a6edc787e2.png)
The JDBC Analytika failed after all.

But all the 4 output worked on my windows client.
What can I provide to you to solve this problem?

**Comment by yurifal** [comment]
Did you do tests on Server using the **same flow** 
(with the four different outputs inside, as on your screenshot)?

Could you please try every connection in it's own flow?
Having the outputs in the same flow would result in error anyways.

**Comment by kaihg** [comment]
I split the test flow into 4 single flows, and the general ODBC, JDBC connector flow test is success.

The ODBC connector by altinity still failed on server.
![image](https://user-images.githubusercontent.com/5411167/159444243-56ac434c-41e9-4a68-b555-e5df5cb34db0.png)
The error message means "Failed to connect to 「」".
When I try the connection on Web UI, it seems success like this:
![image](https://user-images.githubusercontent.com/5411167/159444927-47b028fa-2a4a-494f-a53d-f34b3e160a36.png)
And the JDBC connector by Analytika is as same as that.

> Could you please try every connection in it's own flow?
The tableau connector worked, but isn't for Analytika.

**Comment by artshevchenko** [comment]
@kaihg Hi! We have good news. If you want to run Prep flows on Tableau Server you need to place connector (.taco file) here:
- `[Tableau_Server_Installation_Directory]/data/tabsvc/vizqlserver/Connectors/`
- `[Tableau_Server_Installation_Directory]/data/tabsvc/flowprocessor/Connectors/`
- `[Tableau_Server_Installation_Directory]/data/tabsvc/flowqueryservice/Connectors/`*(if directory exists)*
- `[Tableau_Server_Installation_Directory]/data/tabsvc/flowminerva/Connectors/`*(if directory exists)*

If the changes do not take effect immediately, you may need to restart the server.

**Comment by kaihg** [comment]
@artshevchenko Thank you, the problem has solved !
