### ISSUE TITLE
Package signature verification failed during connection creation

### ISSUE THREAD

**Issue by NikitaUshanov** [analytikaplus/clickhouse-tableau-connector-jdbc#30]
Good afternoon, colleagues. When connecting to ClickHouse via connector JDBC by Analytica Plus, sometimes an error occurs (screenshot).
The error appears on versions 2021.2.2, 2021.2.3, 2021.2.9 Tableau Desktop.
This error started appearing relatively recently.
![image](https://user-images.githubusercontent.com/64222243/160696163-b1ff86e1-b7dc-469c-82e5-b623fe928fe5.png)

**Comment by yurifal** [comment]
Could you please tell the version of the OS? 
Does it help if you try the version 0.2.2 of the Connector?
Does the upgrade to the latest builds of 2021.3 or 2021.4 help?

I'm not able to reproduce the error with version 0.2.2 of the Connector 
together with either 2021.2.9 or 2021.4.4 of Tableau Desktop for Mac.

**Comment by artshevchenko** [comment]
@NikitaUshanov Hi!
[Maybe it will help somehow?](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/issues/19) Can you share the OS version and the exact minor version of Tableau Desktop?

**Comment by NikitaUshanov** [comment]
I apologize for the long response. From what we have been able to record:
MacOS | 0.2.1. taco | 0.3.2.jar | Tableau 2021.2.2
MacOS | 0.2.1. taco | 0.3.2.jar | Tableau 2021.2.3
MacOS | 0.2.1. taco | 0.3.2.jar | Tableau 2021.2.9

**Comment by yurifal** [comment]
Hi @NikitaUshanov  are you still having this issue? have you been able to reproduce it with the latest taco (0.2.2) and the latest version of the JDBC driver (at least 0.3.2-patch7 or above)?
