### ISSUE TITLE
Configuring the driver via .properties

### ISSUE THREAD

**Issue by alexnoz** [analytikaplus/clickhouse-tableau-connector-jdbc#31]
Hi, I'm not a Java developer, so the question is rather noob, is it possible to configure the driver via .properties file? If so, where should I put the file and what options are available? We'd like to configure connection/socket timeouts on the server and not on the client.

**Comment by yurifal** [comment]
Hi @alexnoz , 

Tableau Connector SDK doesn't allow to read from a file when configuring and establishing a connection 
(though reading from the properties file is possible when making the Generic JDBS connection in Desktop).

There is the Advanced tab in our Connector, where you could write the connection settings 
(including the timeouts) in the form of key1=value1,key2=value2 etc. 
Please refer to the README.md on the main GitHub page for the instructions (how to do it).

FYI There are (default server-wide) Settings on the Server side (which could be modified there):
https://clickhouse.com/docs/en/operations/settings/settings/#connect-timeout-receive-timeout-send-timeout
