### ISSUE TITLE
Feature request: add sumIf, countIf, etc. formulas 

### ISSUE THREAD

**Issue by kuntzi** [analytikaplus/clickhouse-tableau-connector-jdbc#32]
This is not an issue, just new feature request.

Could you please add sumIf (SUM_IF), countIf (COUNT_IF) uniqIf (COUNTD_IF), etc. formulas to your connector? 
Performance of native functions in ClickHouse is much better then nested formulas like SUM(CASW WHEN ...) and develoment in Tableau will be much easier.

Thanks

**Comment by yurifal** [comment]
Hi @kuntzi and thank you for the feature request.

While waiting for the Aggregate Combinators to be implemented (written in the dialect.tdd of the Connector), 
you may want to write them "as is" using the RAWSQLAGG functionality (Live Connection only, no extract).

**Comment by kuntzi** [comment]
@yurifal Thanks for excelent idea, I just forgot about this function.

**Comment by yurifal** [comment]
Closed with [this commit](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/commit/c4bc4a729a5506ed38791eb6e11bda6d42fbfc0f).
