### ISSUE TITLE
datename function not working

### ISSUE THREAD

**Issue by vlauzeckas** [analytikaplus/clickhouse-tableau-connector-jdbc#34]
hi, could it be that datename tableau function not working with Analytika JDBC driver?
![image](https://user-images.githubusercontent.com/57217307/169476571-471d4e3c-c07d-4d6c-9b67-940f8c46afce.png)

I would expect "May" to be written here.  Same formula from any other data source:
![image](https://user-images.githubusercontent.com/57217307/169476819-5e1994ac-4130-4665-9e73-c1bb55049e6b.png)

**Comment by yurifal** [comment]
@vlauzeckas thank you for the catch. Indeed, my fault. 
The current DATENAME() function in the connector is actually a DATEPART() one ;-)
Will be corrected in the next release (very soon).

**Comment by vlauzeckas** [comment]
Thank you very much!
