### ISSUE TITLE
readonly mode error

### ISSUE THREAD

**Issue by Egorka31** [analytikaplus/clickhouse-tableau-connector-jdbc#35]
![123](https://user-images.githubusercontent.com/27700327/172424338-8b5a12e5-42d1-4f23-9813-838a8951fe21.jpg)

Have a problem like on photo
Probably I should set readonly = 2, but I don't know where

**Comment by yurifal** [comment]
for the CH **version 20.6 or lower** please try using 
the version [0.3.1-patch of the JDBC driver](https://github.com/ClickHouse/clickhouse-jdbc/releases/tag/v0.3.1-patch)
and the [version 0.1.4 of the Connector](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/releases/tag/v0.1.4).

and please try defining user rights in the database schema (GRANT ... statements), 
not in the Profiles (in the users.xml). this would allow users to set session variables.

**Comment by Egorka31** [comment]
these drivers works for me, thank you!
