### ISSUE TITLE
Errors with dataname function

### ISSUE THREAD

**Issue by vlauzeckas** [analytikaplus/clickhouse-tableau-connector-jdbc#37]
We upgraded from 0.2.2 to 0.2.3 taco file to production and realized that some of our dashboards not working and throwing strange error:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/57217307/180639074-a1297b75-3751-4cd6-9836-9eca5cee898f.png)

as it was production we had quickly to revert back to taco 0.2.2 without proper testing and investigation. It was working fine on desktop tableau version, but throwing errors on the server. 
1. maybe this error gives any clue what is wrong?
2. could it be that data sources created with taco 0.2.2 had to be republished once taco 0.2.3 was installed on the server?

**Comment by yurifal** [comment]
Hi @vlauzeckas , it's hard to suggest anything without reproducing the case in a controlled environment.
Could you please come up with the version numbers of JDBC driver(s) and core products (both TD & TS)?
The OS versions (for both TS and TS) could be of some help, too.

Better way to attack a problem is to publish a wb in question to the test instance of TS, 
then nail down to the exact view / calcs that would reproduce the erratic behaviour.

You can send email to support@analytikaplus.ru (or DM me at y.fal @ analytikaplus.ru ) on this case.
We decide how to reproduce the problem (in my testbed) without compromising any sensitive info you may have.

**Comment by vlauzeckas** [comment]
hi Yuri,
thanks for reply. i managed to reproduce the error in a different environment and investigate it in more detail. seems functions DATENAME throws the error. Example if I use "DATENAME('month', [MyDate])" i get an error in server or desktop.
But function DATEPART('month', [MyDate]) that would give me the same results works perfectly fine. 
Technically i can work out my dashboards with DATEPART, yet DATENAME is a standard tableau function. It would be good to fix this in the future. Your JDBC-based connector is really good. lot of companies will use it.

**Comment by yurifal** [comment]
may I ask the version # of CH you're on?

**Comment by yurifal** [comment]
@vlauzeckas would you get an error with the `DATENAME('week', [MyDate])` ?

**Comment by vlauzeckas** [comment]
CH version: 21.12.3.32
Also this version throwing error: 22.4.5.9

**Comment by vlauzeckas** [comment]
Yes, `DATENAME('week', [MyDate])`
also generate error. 

This is query that have been generated, throwing error if i run directly on clickhouse:

`
SELECT  MIN(CAST(DATENAME(,(CASE WHEN (NOT ISNULL(parseDateTimeBestEffortOrNull(CAST("mv_mvno_data_local"."cdr_date" AS Nullable(String))))) 
THEN parseDateTimeBestEffortOrNull(CAST("mv_mvno_data_local"."cdr_date" AS Nullable(String))) WHEN
(NOT ISNULL(parseDateTimeBestEffortOrNull(CAST("mv_mvno_data_local"."cdr_date" AS Nullable(String))))) THEN parseDateTimeBestEffortOrNull(CAST("mv_mvno_data_local"."cdr_date" AS Nullable(String))) ELSE NULL END)) AS Nullable(String))) AS "Calculation_3195585470056677381"
FROM "itcim"."mv_mvno_data_local" "mv_mvno_data_local"
GROUP BY "cdr_date"`

**Comment by yurifal** [comment]
Fixed in [this commit](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/commit/b59c30a90209cde33c769bf4f46248b8fe39f72b).
