### ISSUE TITLE
toISOWeek / toISOYear request

### ISSUE THREAD

**Issue by javiererrogarcia** [analytikaplus/clickhouse-tableau-connector-jdbc#38]
Hello everyone, we are trying to use Tableau with clickhouse using the analitika plus connector, but all our dashboards use the function toISOWeek / toISOYear, its possible to add in the dialect.tdd the next lines in order to be callabe from tableau?

``
<date-function name='DATEPART' return-type='int'>
  <formula part='isoweek'>toISOWeek(%2)</formula>
  <formula part='isoyear'>toISOYear(%2)</formula>
 </date-function>
 ``
 
 Thank you in advance!

**Comment by yurifal** [comment]
I believe [this commit](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/commit/10bbd90cc75e76b555265527c56f4fe537adf6b8) would do it.
