### ISSUE TITLE
Official ClickHouse Tableau Connector

### ISSUE THREAD

**Issue by genzgd** [analytikaplus/clickhouse-tableau-connector-jdbc#41]
Hi -- I'm an integrations engineer at ClickHouse Inc. and we really like your connector (see our docs here: https://clickhouse.com/docs/en/connect-a-ui/tableau-and-clickhouse). We'd love to discuss moving this project under the "official" ClickHouse umbrella.

We want to work with the Tableau team to bundle ClickHouse natively with the Tableau application using the officially supported clickhouse-jdbc driver and an official "ClickHouse" Tableau connector, and we think this project would be an excellent candidate.  Is that something Analytika Plus would be interested in?  Is there someone we can set up a meeting with?

Thanks!

Geoff Genz
Senior Integrations Engineer, ClickHouse Inc.

**Comment by vlauzeckas** [comment]
yes please, make it an official tableau connector! it is amazing and we use it with joy with Tableau!

**Comment by artshevchenko** [comment]
Hello, Geoff! We have discussed the possibilities of cooperation with Mikhail Shustov, now we are waiting for information from your colleague.

**Comment by mshustov** [comment]
https://exchange.tableau.com/products/1064
