### ISSUE TITLE
Please can you publish the new version with isoYear / isoWeek changes?

### ISSUE THREAD

**Issue by javiererrogarcia** [analytikaplus/clickhouse-tableau-connector-jdbc#42]
Hello everyone we need to use the isoYear / isoWeek please, could you publish the v0.2.5?

Thank you in advance!

**Comment by artshevchenko** [comment]
Hi! Thanks for your patience. [Here is the new release.](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/releases/tag/v0.2.5)
