### ISSUE TITLE
Incorrect return of Datepart function

### ISSUE THREAD

**Issue by vlauzeckas** [analytikaplus/clickhouse-tableau-connector-jdbc#43]
hi,
we have issues while running "datepart" function. I found in your code such line:

`<formula part='weekday'>toDayOfWeek(%2) mod 7 + 1</formula>`

Why do you add this 7+1?

I have tried to run this directly on clickhouse: 
`select toDayOfWeek(  toDate('2022-12-19')) mod 7 + 1`

And it returns **2** where December 19 is Monday.

**Comment by yurifal** [comment]
Hi @vlauzeckas 

Tableau interprets 1 as Sunday (hence 2 as Monday) etc.

**Comment by vlauzeckas** [comment]
as i understand it is configurable on data source level in tableau:
![image](https://user-images.githubusercontent.com/57217307/208431874-7667faab-53ac-478c-a09e-7ddd52c54972.png)

currently if i configure that my  week starts on Monday i get wrong results

**Comment by yurifal** [comment]
Could you please explain what the "wrong results" are?

**Comment by yurifal** [comment]
@vlauzeckas  fyi: 
both DATEPART('weekday', #2022-12-19#) 
and DATEPART('weekday', #2022-12-19#, 'monday') 
do always return 2.

**Comment by vlauzeckas** [comment]
ghmm, actually you are right. i have tested with postgresl and it behaves similarly
