### ISSUE TITLE
ISOWEEKDAY() function implementation 

### ISSUE THREAD

**Issue by vlauzeckas** [analytikaplus/clickhouse-tableau-connector-jdbc#44]
would it be possible to implement ISOWEEKDAY() function on the connector?

**Comment by yurifal** [comment]
We'd be better implementing a full ISO-8601 calendar features:
https://help.tableau.com/current/pro/desktop/en-us/dates_calendar.htm

Working on this in the next release.

**Comment by artshevchenko** [comment]
Hi! You can find this function in the [latest release](https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/releases/tag/v0.2.6).
