### ISSUE TITLE
Can' use isoweek

### ISSUE THREAD

**Issue by javiererrogarcia** [analytikaplus/clickhouse-tableau-connector-jdbc#45]
Hello everyone im trying to use _DATEPART('isoweek',date)_ in my workbook with the new version(0.2.5) but I'm getting an error, can you give me some light?

Best Regards!

**Comment by javiererrogarcia** [comment]
any idea?

**Comment by yurifal** [comment]
Fixing the TDD to support the ISO-8601 in full, stay tuned.
