### ISSUE TITLE
Unable to connect from tableau server 2021.3.8 error FAB9A2C5

### ISSUE THREAD

**Issue by gnaveenkr** [analytikaplus/clickhouse-tableau-connector-jdbc#49]
An error occurred while communicating with ClickHouse JDBC by ANALYTIKA PLUS
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5
connect timed out, server ClickHouseNode(addr=, db=default)@-44420824
Unable to connect to the ClickHouse JDBC by ANALYTIKA PLUS server "". Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.2.5

I am able to connect from tableau desktop 2021.3.8 but when I copy the
jdbc jar file clickhouse-jdbc-0.3.2-patch8-shaded.jar to C:\Program Files\Tableau\Drivers
taco file clickhouse_jdbc_0.2.6.taco copyied to C:\Program Files\Tableau\Connectors

**Comment by yurifal** [comment]
Where the error is coming from? Server? Desktop? 
Is it just for this connection, or any one (to your ClickHouse instance)?
Are you sure the JDBC driver and taco file to be properly installed 
(as described in the README of the connector)?
