### ISSUE TITLE
ISSUE 47D8F526

### ISSUE THREAD

**Issue by gregoryzubenko** [analytikaplus/clickhouse-tableau-connector-jdbc#50]
Hi! What do I do wrong ? Can't connect , says no drivers , but I did everything as it was said. 

![Снимок экрана 2023-04-20 в 16 23 34](https://user-images.githubusercontent.com/115933374/233321821-f7a5a544-be74-41cd-95b2-6a5f5006d608.png)

![image](https://user-images.githubusercontent.com/115933374/233321952-fcd6d31a-098a-458d-8681-e0fa1cabf976.png)

**Comment by vlauzeckas** [comment]
had same one yesterday :). you are using wrong JDBC driver file.
check out exact naming.

V.

**Comment by yurifal** [comment]
https://github.com/ClickHouse/clickhouse-java/releases/download/v0.4.4/clickhouse-jdbc-0.4.4-shaded.jar
OR
https://github.com/ClickHouse/clickhouse-java/releases/download/v0.4.4/clickhouse-jdbc-0.4.4-http.jar

**Comment by gregoryzubenko** [comment]
thank you
