### ISSUE TITLE
Can't connect 

### ISSUE THREAD

**Issue by gregoryzubenko** [analytikaplus/clickhouse-tableau-connector-jdbc#52]
I have so many issues connecting to the clickhouse server , i have just notices that on the instruction you can add the name of the database but I can't see that on my page , is that okay or my doing smthng wrong ? 

![image](https://user-images.githubusercontent.com/115933374/233360845-4f4f2142-f1f6-4f06-9a23-945701aca7ff.png)

**Comment by gregoryzubenko** [comment]
Okay but i still have this issue : 

![image](https://user-images.githubusercontent.com/115933374/233367512-784e1bd4-3424-40ed-9598-1b74f0bc992d.png)

**Comment by yurifal** [comment]
If you connect via **http** (port 8123) you don't need SSL.

**Comment by gregoryzubenko** [comment]
i doesn't change anything

**Comment by gregoryzubenko** [comment]
Thank you! I have tried using ODBC but I can't set up drivers either

**Comment by gregoryzubenko** [comment]
This is the querry that created my user for the database : 

CREATE USER analytics IDENTIFIED WITH plaintext_password BY 'xxx' SETTINGS PROFILE 'readonly'
GRANT SHOW TABLES, SELECT ON database.* TO analytics 

What should i change in it to be able to work with tableaU?

**Comment by yurifal** [comment]
Just remove the SETTINGS PROFILE 'readonly' from the CREATE statement

**Comment by EduarddOjog** [comment]
Hi,

I got this error message.

![image](https://user-images.githubusercontent.com/106492573/234535948-bc0df08a-0122-4451-9ea1-cb776b805423.png)

Do you have any idea why?

**Comment by yurifal** [comment]
No idea. 
Could you please share the connection screen, 
or describe what are you trying to accomplish?

**Comment by vlauzeckas** [comment]
do you get this error while connecting to clickhouse or already when trying to build data source from view/table?

**Comment by EduarddOjog** [comment]
> ![image](https://user-images.githubusercontent.com/106492573/234566386-8daeb065-0f77-4653-94fa-f6e6ad0b7e82.png)

i got this error when i tried to connect

**Comment by yurifal** [comment]
Can you make a successful connection to this CH instance (localhost:443)
with any other SQL client via JDBC (for example DBeaver)? Could you please share?

**Comment by EduarddOjog** [comment]
I have successul connection to CH via VS code and DBeaver. Also do you know what exactly driver i need to paste in tableau?

**Comment by yurifal** [comment]
Could you please share the DBeaver connection screen (with the actual hostname / username dimmed)?

**Comment by EduarddOjog** [comment]
![image](https://user-images.githubusercontent.com/106492573/234571149-c8307d83-c100-4333-b8d4-f72a05b85f46.png)

**Comment by yurifal** [comment]
In Tableau set the SSL (checkbox) to ON

**Comment by EduarddOjog** [comment]
I tried also with that SSL checked but same error.

**Comment by yurifal** [comment]
OK, let's test in another way.
Could you please connect to the play.clickhouse.com:443 
using the explorer / clickhouse as the user / password? 
<img width="503" alt="Screenshot 2023-04-26 at 15 19 58" src="https://user-images.githubusercontent.com/2496788/234572846-1db923a4-f4be-408d-8b54-03d51ac4597f.png">
If successful, it would mean that you have both the JDBC driver and the Tableau CH connector set up properly.

**Comment by EduarddOjog** [comment]
Server: play.clickhouse.com
Port: 443
Username: explorer
Password: password?

are these credentials correct?

**Comment by yurifal** [comment]
Password : clickhouse

**Comment by EduarddOjog** [comment]
Done guys. I did it. Thank you!

**Comment by EduarddOjog** [comment]
Hi again,
When I`m trying to publish my workbook I got this error message.
![image](https://user-images.githubusercontent.com/106492573/234782420-62f523f3-635b-4611-88ac-5ac07a304dd8.png)
Do you know what kind of tableau version should I use or how to install this plugin..I dont know..

**Comment by yurifal** [comment]
Publishing a workbook on the server would require 
both the JDBC driver and the Connector 
to be installed on the server host.

The README contains the instructions (how to install on a server).

**Comment by EduarddOjog** [comment]
Could you help me with the link to the correctly README?

**Comment by EduarddOjog** [comment]
And I also dont have a tableau server. Just a Tableau Online

**Comment by yurifal** [comment]
https://github.com/analytikaplus/clickhouse-tableau-connector-jdbc/blob/main/README.md

Tableau Online (Cloud) -- no way to connect to CH Live.
The only option is using the Bridge (hence the extract):
https://help.tableau.com/current/online/en-us/data_fresh_sync_section.htm
