### ISSUE TITLE
Error Code: 4D78F526 

### ISSUE THREAD

**Issue by VolodymyrDzebliuk** [analytikaplus/clickhouse-tableau-connector-jdbc#53]
Hi! What do I do wrong ? Can't connect , says no drivers , but I did everything as it was said.

<img width="491" alt="Screenshot 2023-04-21 at 17 30 28" src="https://user-images.githubusercontent.com/131468468/233666710-081399e2-5d21-461f-b5dc-6f75c84663f8.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/131468468/233667164-9397492c-ac03-4625-9f78-c6b008cf268a.png">

**Comment by VolodymyrDzebliuk** [comment]
> This one? https://github.com/ClickHouse/clickhouse-java/releases/download/v0.4.4/clickhouse-jdbc-0.4.4-http.jar
> 
> Which directory is it in?

Yes
There is a directory in the screenshot
~Library/Tableau/Drivers

**Comment by yurifal** [comment]
The ~/Library/Tableau/Drivers does exist when Tableau Desktop is installed.
A tilde ~ is used to represent the user's "home folder", 
thus the absolute path would be 
/Users/$USER/Library/Tableau/Drivers

**Comment by VolodymyrDzebliuk** [comment]
Thanks
Works
